// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { AzureClouds, AzureSupportedClouds } from "./static-helpers/cloudSettingHelpers.js";
import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ContainerAppsAPIClient } from "./containerAppsAPIClient.js";
export type { SimplePollerLike } from "./static-helpers/simplePollerHelpers.js";
export type { RestorePollerOptions } from "./restorePollerHelpers.js";
export { restorePoller } from "./restorePollerHelpers.js";
export type {
  DefaultErrorResponse,
  DefaultErrorResponseError,
  DefaultErrorResponseErrorDetailsItem,
  JobExecution,
  JobExecutionProperties,
  JobExecutionRunningState,
  JobExecutionTemplate,
  JobExecutionContainer,
  EnvironmentVar,
  ContainerResources,
  ProxyResource,
  Resource,
  SystemData,
  CreatedByType,
  OperationDetail,
  OperationDisplay,
  SessionPool,
  SessionPoolProperties,
  ContainerType,
  PoolManagementType,
  ScaleConfiguration,
  SessionPoolSecret,
  DynamicPoolConfiguration,
  LifecycleConfiguration,
  LifecycleType,
  CustomContainerTemplate,
  SessionRegistryCredentials,
  SessionContainer,
  SessionContainerResources,
  SessionIngress,
  SessionNetworkConfiguration,
  SessionNetworkStatus,
  SessionPoolProvisioningState,
  ManagedIdentitySetting,
  SessionPoolIdentityLifeCycle,
  ManagedServiceIdentity,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  TrackedResource,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  SessionPoolUpdatableProperties,
  SessionPoolUpdatablePropertiesProperties,
  SourceControl,
  SourceControlProperties,
  SourceControlOperationState,
  GithubActionConfiguration,
  RegistryInfo,
  AzureCredentials,
  ContainerApp,
  ContainerAppProperties,
  ContainerAppProvisioningState,
  ContainerAppRunningStatus,
  Configuration,
  Secret,
  ActiveRevisionsMode,
  Ingress,
  IngressTransportMethod,
  TrafficWeight,
  CustomDomain,
  BindingType,
  IpSecurityRestrictionRule,
  Action,
  IngressStickySessions,
  Affinity,
  IngressClientCertificateMode,
  CorsPolicy,
  IngressPortMapping,
  RegistryCredentials,
  Dapr,
  AppProtocol,
  LogLevel,
  DaprAppHealth,
  Runtime,
  RuntimeJava,
  Service,
  IdentitySettings,
  IdentitySettingsLifeCycle,
  Template,
  InitContainer,
  Container,
  ContainerAppProbe,
  ContainerAppProbeHttpGet,
  ContainerAppProbeHttpGetHttpHeadersItem,
  Scheme,
  ContainerAppProbeTcpSocket,
  Type,
  Scale,
  ScaleRule,
  QueueScaleRule,
  ScaleRuleAuth,
  CustomScaleRule,
  HttpScaleRule,
  TcpScaleRule,
  Volume,
  StorageType,
  SecretVolumeItem,
  ServiceBind,
  ExtendedLocation,
  ExtendedLocationTypes,
  Kind,
  BaseContainer,
  VolumeMount,
  CustomHostnameAnalysisResult,
  DnsVerificationTestResult,
  CustomHostnameAnalysisResultCustomDomainVerificationFailureInfo,
  CustomHostnameAnalysisResultCustomDomainVerificationFailureInfoDetailsItem,
  SecretsCollection,
  ContainerAppSecret,
  ContainerAppAuthToken,
  ContainerAppAuthTokenProperties,
  Revision,
  RevisionProperties,
  RevisionHealthState,
  RevisionProvisioningState,
  RevisionRunningState,
  Replica,
  ReplicaProperties,
  ContainerAppReplicaRunningState,
  ReplicaContainer,
  ContainerAppContainerRunningState,
  ReplicaCollection,
  JavaComponent,
  JavaComponentProperties,
  JavaComponentPropertiesUnion,
  JavaComponentType,
  JavaComponentProvisioningState,
  JavaComponentConfigurationProperty,
  JavaComponentPropertiesScale,
  JavaComponentServiceBind,
  SpringBootAdminComponent,
  JavaComponentIngress,
  SpringCloudEurekaComponent,
  SpringCloudConfigComponent,
  LogicApp,
  WorkflowEnvelope,
  WorkflowEnvelopeProperties,
  WorkflowState,
  WorkflowHealth,
  WorkflowHealthState,
  ErrorEntity,
  WorkflowKind,
  AuthConfig,
  AuthConfigProperties,
  AuthPlatform,
  GlobalValidation,
  UnauthenticatedClientActionV2,
  IdentityProviders,
  AzureActiveDirectory,
  AzureActiveDirectoryRegistration,
  AzureActiveDirectoryLogin,
  AzureActiveDirectoryValidation,
  JwtClaimChecks,
  DefaultAuthorizationPolicy,
  AllowedPrincipals,
  Facebook,
  AppRegistration,
  LoginScopes,
  GitHub,
  ClientRegistration,
  Google,
  AllowedAudiencesValidation,
  Twitter,
  TwitterRegistration,
  Apple,
  AppleRegistration,
  AzureStaticWebApps,
  AzureStaticWebAppsRegistration,
  CustomOpenIdConnectProvider,
  OpenIdConnectRegistration,
  OpenIdConnectClientCredential,
  OpenIdConnectConfig,
  OpenIdConnectLogin,
  Login,
  LoginRoutes,
  TokenStore,
  BlobStorageTokenStore,
  CookieExpiration,
  CookieExpirationConvention,
  Nonce,
  HttpSettings,
  HttpSettingsRoutes,
  ForwardProxy,
  ForwardProxyConvention,
  EncryptionSettings,
  ConnectedEnvironment,
  ConnectedEnvironmentProperties,
  ConnectedEnvironmentProvisioningState,
  CustomDomainConfiguration,
  CertificateKeyVaultProperties,
  ConnectedEnvironmentPatchResource,
  ResourceTags,
  CheckNameAvailabilityRequest,
  CheckNameAvailabilityResponse,
  CheckNameAvailabilityReason,
  Certificate,
  CertificateProperties,
  CertificateProvisioningState,
  CertificatePatch,
  ManagedEnvironment,
  ManagedEnvironmentProperties,
  EnvironmentProvisioningState,
  VnetConfiguration,
  AppLogsConfiguration,
  LogAnalyticsConfiguration,
  WorkloadProfile,
  KedaConfiguration,
  DaprConfiguration,
  ManagedEnvironmentPropertiesPeerAuthentication,
  Mtls,
  ManagedEnvironmentPropertiesPeerTrafficConfiguration,
  ManagedEnvironmentPropertiesPeerTrafficConfigurationEncryption,
  IngressConfiguration,
  PrivateEndpointConnection,
  PrivateEndpointConnectionProperties,
  PrivateEndpoint,
  PrivateLinkServiceConnectionState,
  PrivateEndpointServiceConnectionStatus,
  PrivateEndpointConnectionProvisioningState,
  PublicNetworkAccess,
  EnvironmentAuthToken,
  EnvironmentAuthTokenProperties,
  WorkloadProfileStates,
  WorkloadProfileStatesProperties,
  DaprComponent,
  DaprComponentProperties,
  DaprMetadata,
  DaprComponentProvisioningState,
  DaprSecretsCollection,
  DaprSecret,
  ConnectedEnvironmentStorage,
  ConnectedEnvironmentStorageProperties,
  ConnectedEnvironmentStorageProvisioningState,
  AzureFileProperties,
  SecretKeyVaultProperties,
  AccessMode,
  ConnectedEnvironmentStoragesCollection,
  ManagedCertificate,
  ManagedCertificateProperties,
  ManagedCertificateDomainControlValidation,
  ManagedCertificatePatch,
  MaintenanceConfigurationResource,
  ScheduledEntries,
  ScheduledEntry,
  WeekDay,
  ManagedEnvironmentStorage,
  ManagedEnvironmentStorageProperties,
  NfsAzureFileProperties,
  ManagedEnvironmentStoragesCollection,
  Job,
  JobProperties,
  JobProvisioningState,
  JobConfiguration,
  TriggerType,
  JobConfigurationManualTriggerConfig,
  JobConfigurationScheduleTriggerConfig,
  JobConfigurationEventTriggerConfig,
  JobScale,
  JobScaleRule,
  JobTemplate,
  JobPatchProperties,
  JobPatchPropertiesProperties,
  JobExecutionBase,
  ContainerAppJobExecutions,
  JobSecretsCollection,
  DiagnosticsCollection,
  Diagnostics,
  DiagnosticsProperties,
  DiagnosticsDefinition,
  DiagnosticSupportTopic,
  DiagnosticsDataApiResponse,
  DiagnosticDataTableResponseObject,
  DiagnosticDataTableResponseColumn,
  DiagnosticRendering,
  DiagnosticsStatus,
  DiagnosticDataProviderMetadata,
  DiagnosticDataProviderMetadataPropertyBagItem,
  PrivateLinkResource,
  PrivateLinkResourceProperties,
  HttpRouteConfig,
  HttpRouteConfigProperties,
  HttpRouteProvisioningState,
  HttpRouteProvisioningErrors,
  HttpRouteRule,
  HttpRouteTarget,
  HttpRoute,
  HttpRouteMatch,
  HttpRouteAction,
  AvailableWorkloadProfile,
  AvailableWorkloadProfileProperties,
  Applicability,
  BillingMeterCollection,
  BillingMeter,
  BillingMeterProperties,
  Usage,
  UsageName,
  GetCustomDomainVerificationIdResponse,
} from "./models/index.js";
export {
  KnownJobExecutionRunningState,
  KnownCreatedByType,
  KnownContainerType,
  KnownPoolManagementType,
  KnownLifecycleType,
  KnownSessionNetworkStatus,
  KnownSessionPoolProvisioningState,
  KnownSessionPoolIdentityLifeCycle,
  KnownManagedServiceIdentityType,
  KnownSourceControlOperationState,
  KnownContainerAppProvisioningState,
  KnownContainerAppRunningStatus,
  KnownActiveRevisionsMode,
  KnownIngressTransportMethod,
  KnownBindingType,
  KnownAction,
  KnownAffinity,
  KnownIngressClientCertificateMode,
  KnownAppProtocol,
  KnownLogLevel,
  KnownIdentitySettingsLifeCycle,
  KnownScheme,
  KnownType,
  KnownStorageType,
  KnownExtendedLocationTypes,
  KnownKind,
  KnownRevisionHealthState,
  KnownRevisionProvisioningState,
  KnownRevisionRunningState,
  KnownContainerAppReplicaRunningState,
  KnownContainerAppContainerRunningState,
  KnownJavaComponentType,
  KnownJavaComponentProvisioningState,
  KnownWorkflowState,
  KnownWorkflowKind,
  KnownConnectedEnvironmentProvisioningState,
  KnownCheckNameAvailabilityReason,
  KnownCertificateProvisioningState,
  KnownEnvironmentProvisioningState,
  KnownPrivateEndpointServiceConnectionStatus,
  KnownPrivateEndpointConnectionProvisioningState,
  KnownPublicNetworkAccess,
  KnownDaprComponentProvisioningState,
  KnownConnectedEnvironmentStorageProvisioningState,
  KnownAccessMode,
  KnownManagedCertificateDomainControlValidation,
  KnownJobProvisioningState,
  KnownTriggerType,
  KnownHttpRouteProvisioningState,
  KnownApplicability,
  KnownVersions,
} from "./models/index.js";
export type {
  ContainerAppsAPIClientOptionalParams,
  JobExecutionOptionalParams,
  GetCustomDomainVerificationIdOptionalParams,
} from "./api/index.js";
export type { AvailableWorkloadProfilesListOptionalParams } from "./api/availableWorkloadProfiles/index.js";
export type { BillingMetersGetOptionalParams } from "./api/billingMeters/index.js";
export type {
  CertificatesListOptionalParams,
  CertificatesDeleteOptionalParams,
  CertificatesUpdateOptionalParams,
  CertificatesCreateOrUpdateOptionalParams,
  CertificatesGetOptionalParams,
} from "./api/certificates/index.js";
export type {
  ConnectedEnvironmentsCheckNameAvailabilityOptionalParams,
  ConnectedEnvironmentsListBySubscriptionOptionalParams,
  ConnectedEnvironmentsListByResourceGroupOptionalParams,
  ConnectedEnvironmentsDeleteOptionalParams,
  ConnectedEnvironmentsUpdateOptionalParams,
  ConnectedEnvironmentsCreateOrUpdateOptionalParams,
  ConnectedEnvironmentsGetOptionalParams,
} from "./api/connectedEnvironments/index.js";
export type {
  ConnectedEnvironmentsCertificatesListOptionalParams,
  ConnectedEnvironmentsCertificatesDeleteOptionalParams,
  ConnectedEnvironmentsCertificatesUpdateOptionalParams,
  ConnectedEnvironmentsCertificatesCreateOrUpdateOptionalParams,
  ConnectedEnvironmentsCertificatesGetOptionalParams,
} from "./api/connectedEnvironmentsCertificates/index.js";
export type {
  ConnectedEnvironmentsDaprComponentsListSecretsOptionalParams,
  ConnectedEnvironmentsDaprComponentsListOptionalParams,
  ConnectedEnvironmentsDaprComponentsDeleteOptionalParams,
  ConnectedEnvironmentsDaprComponentsCreateOrUpdateOptionalParams,
  ConnectedEnvironmentsDaprComponentsGetOptionalParams,
} from "./api/connectedEnvironmentsDaprComponents/index.js";
export type {
  ConnectedEnvironmentsStoragesListOptionalParams,
  ConnectedEnvironmentsStoragesDeleteOptionalParams,
  ConnectedEnvironmentsStoragesCreateOrUpdateOptionalParams,
  ConnectedEnvironmentsStoragesGetOptionalParams,
} from "./api/connectedEnvironmentsStorages/index.js";
export type {
  ContainerAppsStopOptionalParams,
  ContainerAppsStartOptionalParams,
  ContainerAppsGetAuthTokenOptionalParams,
  ContainerAppsListSecretsOptionalParams,
  ContainerAppsListCustomHostNameAnalysisOptionalParams,
  ContainerAppsListBySubscriptionOptionalParams,
  ContainerAppsListByResourceGroupOptionalParams,
  ContainerAppsDeleteOptionalParams,
  ContainerAppsUpdateOptionalParams,
  ContainerAppsCreateOrUpdateOptionalParams,
  ContainerAppsGetOptionalParams,
} from "./api/containerApps/index.js";
export type {
  ContainerAppsAuthConfigsListByContainerAppOptionalParams,
  ContainerAppsAuthConfigsDeleteOptionalParams,
  ContainerAppsAuthConfigsCreateOrUpdateOptionalParams,
  ContainerAppsAuthConfigsGetOptionalParams,
} from "./api/containerAppsAuthConfigs/index.js";
export type {
  ContainerAppsDiagnosticsGetDetectorOptionalParams,
  ContainerAppsDiagnosticsListDetectorsOptionalParams,
  ContainerAppsDiagnosticsGetRootOptionalParams,
  ContainerAppsDiagnosticsListRevisionsOptionalParams,
  ContainerAppsDiagnosticsGetRevisionOptionalParams,
} from "./api/containerAppsDiagnostics/index.js";
export type {
  ContainerAppsRevisionReplicasListReplicasOptionalParams,
  ContainerAppsRevisionReplicasGetReplicaOptionalParams,
} from "./api/containerAppsRevisionReplicas/index.js";
export type {
  ContainerAppsRevisionsRestartRevisionOptionalParams,
  ContainerAppsRevisionsDeactivateRevisionOptionalParams,
  ContainerAppsRevisionsActivateRevisionOptionalParams,
  ContainerAppsRevisionsListRevisionsOptionalParams,
  ContainerAppsRevisionsGetRevisionOptionalParams,
} from "./api/containerAppsRevisions/index.js";
export type {
  ContainerAppsSessionPoolsListBySubscriptionOptionalParams,
  ContainerAppsSessionPoolsListByResourceGroupOptionalParams,
  ContainerAppsSessionPoolsDeleteOptionalParams,
  ContainerAppsSessionPoolsUpdateOptionalParams,
  ContainerAppsSessionPoolsCreateOrUpdateOptionalParams,
  ContainerAppsSessionPoolsGetOptionalParams,
} from "./api/containerAppsSessionPools/index.js";
export type {
  ContainerAppsSourceControlsListByContainerAppOptionalParams,
  ContainerAppsSourceControlsDeleteOptionalParams,
  ContainerAppsSourceControlsCreateOrUpdateOptionalParams,
  ContainerAppsSourceControlsGetOptionalParams,
} from "./api/containerAppsSourceControls/index.js";
export type {
  DaprComponentsListSecretsOptionalParams,
  DaprComponentsListOptionalParams,
  DaprComponentsDeleteOptionalParams,
  DaprComponentsCreateOrUpdateOptionalParams,
  DaprComponentsGetOptionalParams,
} from "./api/daprComponents/index.js";
export type {
  HttpRouteConfigListOptionalParams,
  HttpRouteConfigDeleteOptionalParams,
  HttpRouteConfigUpdateOptionalParams,
  HttpRouteConfigCreateOrUpdateOptionalParams,
  HttpRouteConfigGetOptionalParams,
} from "./api/httpRouteConfig/index.js";
export type {
  JavaComponentsListOptionalParams,
  JavaComponentsDeleteOptionalParams,
  JavaComponentsUpdateOptionalParams,
  JavaComponentsCreateOrUpdateOptionalParams,
  JavaComponentsGetOptionalParams,
} from "./api/javaComponents/index.js";
export type {
  JobsGetDetectorOptionalParams,
  JobsListDetectorsOptionalParams,
  JobsProxyGetOptionalParams,
  JobsStopExecutionOptionalParams,
  JobsListSecretsOptionalParams,
  JobsStopMultipleExecutionsOptionalParams,
  JobsStartOptionalParams,
  JobsListBySubscriptionOptionalParams,
  JobsListByResourceGroupOptionalParams,
  JobsDeleteOptionalParams,
  JobsUpdateOptionalParams,
  JobsCreateOrUpdateOptionalParams,
  JobsGetOptionalParams,
} from "./api/jobs/index.js";
export type { JobsExecutionsListOptionalParams } from "./api/jobsExecutions/index.js";
export type {
  LogicAppsListWorkflowsOptionalParams,
  LogicAppsGetWorkflowOptionalParams,
  LogicAppsListWorkflowsConnectionsOptionalParams,
  LogicAppsDeleteOptionalParams,
  LogicAppsCreateOrUpdateOptionalParams,
  LogicAppsGetOptionalParams,
} from "./api/logicApps/index.js";
export type {
  MaintenanceConfigurationsListOptionalParams,
  MaintenanceConfigurationsDeleteOptionalParams,
  MaintenanceConfigurationsCreateOrUpdateOptionalParams,
  MaintenanceConfigurationsGetOptionalParams,
} from "./api/maintenanceConfigurations/index.js";
export type {
  ManagedCertificatesListOptionalParams,
  ManagedCertificatesDeleteOptionalParams,
  ManagedCertificatesUpdateOptionalParams,
  ManagedCertificatesCreateOrUpdateOptionalParams,
  ManagedCertificatesGetOptionalParams,
} from "./api/managedCertificates/index.js";
export type {
  ManagedEnvironmentDiagnosticsGetDetectorOptionalParams,
  ManagedEnvironmentDiagnosticsListDetectorsOptionalParams,
} from "./api/managedEnvironmentDiagnostics/index.js";
export type {
  ManagedEnvironmentPrivateEndpointConnectionsListOptionalParams,
  ManagedEnvironmentPrivateEndpointConnectionsDeleteOptionalParams,
  ManagedEnvironmentPrivateEndpointConnectionsCreateOrUpdateOptionalParams,
  ManagedEnvironmentPrivateEndpointConnectionsGetOptionalParams,
} from "./api/managedEnvironmentPrivateEndpointConnections/index.js";
export type { ManagedEnvironmentPrivateLinkResourcesListOptionalParams } from "./api/managedEnvironmentPrivateLinkResources/index.js";
export type {
  ManagedEnvironmentsListWorkloadProfileStatesOptionalParams,
  ManagedEnvironmentsGetAuthTokenOptionalParams,
  ManagedEnvironmentsListBySubscriptionOptionalParams,
  ManagedEnvironmentsListByResourceGroupOptionalParams,
  ManagedEnvironmentsDeleteOptionalParams,
  ManagedEnvironmentsUpdateOptionalParams,
  ManagedEnvironmentsCreateOrUpdateOptionalParams,
  ManagedEnvironmentsGetOptionalParams,
} from "./api/managedEnvironments/index.js";
export type { ManagedEnvironmentsDiagnosticsGetRootOptionalParams } from "./api/managedEnvironmentsDiagnostics/index.js";
export type {
  ManagedEnvironmentsStoragesListOptionalParams,
  ManagedEnvironmentsStoragesDeleteOptionalParams,
  ManagedEnvironmentsStoragesCreateOrUpdateOptionalParams,
  ManagedEnvironmentsStoragesGetOptionalParams,
} from "./api/managedEnvironmentsStorages/index.js";
export type { ManagedEnvironmentUsagesListOptionalParams } from "./api/managedEnvironmentUsages/index.js";
export type { NamespacesCheckNameAvailabilityOptionalParams } from "./api/namespaces/index.js";
export type { OperationsListOptionalParams } from "./api/operations/index.js";
export type { UsagesListOptionalParams } from "./api/usages/index.js";
export type {
  AvailableWorkloadProfilesOperations,
  BillingMetersOperations,
  CertificatesOperations,
  ConnectedEnvironmentsOperations,
  ConnectedEnvironmentsCertificatesOperations,
  ConnectedEnvironmentsDaprComponentsOperations,
  ConnectedEnvironmentsStoragesOperations,
  ContainerAppsOperations,
  ContainerAppsAuthConfigsOperations,
  ContainerAppsDiagnosticsOperations,
  ContainerAppsRevisionReplicasOperations,
  ContainerAppsRevisionsOperations,
  ContainerAppsSessionPoolsOperations,
  ContainerAppsSourceControlsOperations,
  DaprComponentsOperations,
  HttpRouteConfigOperations,
  JavaComponentsOperations,
  JobsOperations,
  JobsExecutionsOperations,
  LogicAppsOperations,
  MaintenanceConfigurationsOperations,
  ManagedCertificatesOperations,
  ManagedEnvironmentDiagnosticsOperations,
  ManagedEnvironmentPrivateEndpointConnectionsOperations,
  ManagedEnvironmentPrivateLinkResourcesOperations,
  ManagedEnvironmentsOperations,
  ManagedEnvironmentsDiagnosticsOperations,
  ManagedEnvironmentsStoragesOperations,
  ManagedEnvironmentUsagesOperations,
  NamespacesOperations,
  OperationsOperations,
  UsagesOperations,
} from "./classic/index.js";
export type { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
export { AzureClouds };
export type { AzureSupportedClouds };
export { RestError, isRestError } from "@azure/core-rest-pipeline";
